[package]
name = "summerequinox/easystate"
version = "1.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "src/**", "default.project.json"]
exclude = ["build", ".vscode", ".github", "*.md", "*.rbxl", "*.rbxlx", "*.lock", "*.gitignore", "tests", "examples", "docs"]
authors = ["SummerEquinox"]