[package]
name = "summerequinox/easystate"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "src/**", "wally.toml", "wally.lock"]
authors = ["SummerEquinox (https://github.com/SummerEquinox)"]